### ISSUE TITLE
Review for delete member function

### ISSUE THREAD

**Issue by gavindang2911** [gavindang2911/team-member-management#1]
I believe that I have done 95% implementation for the app. Every function works perfectly.

Right now, we can delete every member from the list by the Delete button. 

However, I want to make sure that, if a person is an admin, we are not allowed to delete him from the list by the delete button?

Do you think I am on the right track?

The screenshots are attached in the readme for your review

@reshavsingla

**Comment by reshavsingla** [comment]
yes

**Comment by reshavsingla** [comment]
Another feedback: Can you try using generic views: https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/ for the `views`

**Comment by gavindang2911** [comment]
I have made some changes regarding your feedback by using generic views.

Please let me know if there is anything else I can do to advance my implementation

@reshavsingla
